dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
addons:
  postgresql: 12.3
  apt:
    packages:
      - postgresql-12.3-postgis-3.0
before_script:
  - psql -c -U postgres "CREATE EXTENSION postgis;"
  - psql -c -U postgres "CREATE USER orbisgis WITH PASSWORD 'orbisgis';"
  - psql -c -U postgres "CREATE DATABASE orbisgis_db;"
  - psql -c -U postgres "GRANT ALL PRIVILEGES ON DATABASE orbisgis_db TO orbisgis;"
env:
  global:
    - CODECOV_TOKEN="a13a8a20-e044-4aba-b060-9a3c712f360b"
script: mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)